/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SupportRouteImport } from './routes/support'
import { Route as FeedbackRouteImport } from './routes/feedback'
import { Route as SeekerRouteImport } from './routes/_seeker'
import { Route as OwnerRouteImport } from './routes/_owner'
import { Route as AdminRouteImport } from './routes/_admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SeekerSignupRouteImport } from './routes/seeker.signup'
import { Route as SeekerLoginRouteImport } from './routes/seeker.login'
import { Route as OwnerSignupRouteImport } from './routes/owner.signup'
import { Route as OwnerLoginRouteImport } from './routes/owner.login'
import { Route as SeekerSeekerRouteImport } from './routes/_seeker/seeker'
import { Route as SeekerSavedRouteImport } from './routes/_seeker/saved'
import { Route as SeekerBrowseRouteImport } from './routes/_seeker/browse'
import { Route as OwnerPublishRouteImport } from './routes/_owner/publish'
import { Route as OwnerOwnerRouteImport } from './routes/_owner/owner'
import { Route as AdminAdminRouteImport } from './routes/_admin/admin'
import { Route as SeekerSpacesIdRouteImport } from './routes/_seeker/spaces.$id'

const SupportRoute = SupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => rootRouteImport,
} as any)
const FeedbackRoute = FeedbackRouteImport.update({
  id: '/feedback',
  path: '/feedback',
  getParentRoute: () => rootRouteImport,
} as any)
const SeekerRoute = SeekerRouteImport.update({
  id: '/_seeker',
  getParentRoute: () => rootRouteImport,
} as any)
const OwnerRoute = OwnerRouteImport.update({
  id: '/_owner',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/_admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SeekerSignupRoute = SeekerSignupRouteImport.update({
  id: '/seeker/signup',
  path: '/seeker/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const SeekerLoginRoute = SeekerLoginRouteImport.update({
  id: '/seeker/login',
  path: '/seeker/login',
  getParentRoute: () => rootRouteImport,
} as any)
const OwnerSignupRoute = OwnerSignupRouteImport.update({
  id: '/owner/signup',
  path: '/owner/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const OwnerLoginRoute = OwnerLoginRouteImport.update({
  id: '/owner/login',
  path: '/owner/login',
  getParentRoute: () => rootRouteImport,
} as any)
const SeekerSeekerRoute = SeekerSeekerRouteImport.update({
  id: '/seeker',
  path: '/seeker',
  getParentRoute: () => SeekerRoute,
} as any)
const SeekerSavedRoute = SeekerSavedRouteImport.update({
  id: '/saved',
  path: '/saved',
  getParentRoute: () => SeekerRoute,
} as any)
const SeekerBrowseRoute = SeekerBrowseRouteImport.update({
  id: '/browse',
  path: '/browse',
  getParentRoute: () => SeekerRoute,
} as any)
const OwnerPublishRoute = OwnerPublishRouteImport.update({
  id: '/publish',
  path: '/publish',
  getParentRoute: () => OwnerRoute,
} as any)
const OwnerOwnerRoute = OwnerOwnerRouteImport.update({
  id: '/owner',
  path: '/owner',
  getParentRoute: () => OwnerRoute,
} as any)
const AdminAdminRoute = AdminAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AdminRoute,
} as any)
const SeekerSpacesIdRoute = SeekerSpacesIdRouteImport.update({
  id: '/spaces/$id',
  path: '/spaces/$id',
  getParentRoute: () => SeekerRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/feedback': typeof FeedbackRoute
  '/support': typeof SupportRoute
  '/admin': typeof AdminAdminRoute
  '/owner': typeof OwnerOwnerRoute
  '/publish': typeof OwnerPublishRoute
  '/browse': typeof SeekerBrowseRoute
  '/saved': typeof SeekerSavedRoute
  '/seeker': typeof SeekerSeekerRoute
  '/owner/login': typeof OwnerLoginRoute
  '/owner/signup': typeof OwnerSignupRoute
  '/seeker/login': typeof SeekerLoginRoute
  '/seeker/signup': typeof SeekerSignupRoute
  '/spaces/$id': typeof SeekerSpacesIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/feedback': typeof FeedbackRoute
  '/support': typeof SupportRoute
  '/admin': typeof AdminAdminRoute
  '/owner': typeof OwnerOwnerRoute
  '/publish': typeof OwnerPublishRoute
  '/browse': typeof SeekerBrowseRoute
  '/saved': typeof SeekerSavedRoute
  '/seeker': typeof SeekerSeekerRoute
  '/owner/login': typeof OwnerLoginRoute
  '/owner/signup': typeof OwnerSignupRoute
  '/seeker/login': typeof SeekerLoginRoute
  '/seeker/signup': typeof SeekerSignupRoute
  '/spaces/$id': typeof SeekerSpacesIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_admin': typeof AdminRouteWithChildren
  '/_owner': typeof OwnerRouteWithChildren
  '/_seeker': typeof SeekerRouteWithChildren
  '/feedback': typeof FeedbackRoute
  '/support': typeof SupportRoute
  '/_admin/admin': typeof AdminAdminRoute
  '/_owner/owner': typeof OwnerOwnerRoute
  '/_owner/publish': typeof OwnerPublishRoute
  '/_seeker/browse': typeof SeekerBrowseRoute
  '/_seeker/saved': typeof SeekerSavedRoute
  '/_seeker/seeker': typeof SeekerSeekerRoute
  '/owner/login': typeof OwnerLoginRoute
  '/owner/signup': typeof OwnerSignupRoute
  '/seeker/login': typeof SeekerLoginRoute
  '/seeker/signup': typeof SeekerSignupRoute
  '/_seeker/spaces/$id': typeof SeekerSpacesIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/feedback'
    | '/support'
    | '/admin'
    | '/owner'
    | '/publish'
    | '/browse'
    | '/saved'
    | '/seeker'
    | '/owner/login'
    | '/owner/signup'
    | '/seeker/login'
    | '/seeker/signup'
    | '/spaces/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/feedback'
    | '/support'
    | '/admin'
    | '/owner'
    | '/publish'
    | '/browse'
    | '/saved'
    | '/seeker'
    | '/owner/login'
    | '/owner/signup'
    | '/seeker/login'
    | '/seeker/signup'
    | '/spaces/$id'
  id:
    | '__root__'
    | '/'
    | '/_admin'
    | '/_owner'
    | '/_seeker'
    | '/feedback'
    | '/support'
    | '/_admin/admin'
    | '/_owner/owner'
    | '/_owner/publish'
    | '/_seeker/browse'
    | '/_seeker/saved'
    | '/_seeker/seeker'
    | '/owner/login'
    | '/owner/signup'
    | '/seeker/login'
    | '/seeker/signup'
    | '/_seeker/spaces/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  OwnerRoute: typeof OwnerRouteWithChildren
  SeekerRoute: typeof SeekerRouteWithChildren
  FeedbackRoute: typeof FeedbackRoute
  SupportRoute: typeof SupportRoute
  OwnerLoginRoute: typeof OwnerLoginRoute
  OwnerSignupRoute: typeof OwnerSignupRoute
  SeekerLoginRoute: typeof SeekerLoginRoute
  SeekerSignupRoute: typeof SeekerSignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/support': {
      id: '/support'
      path: '/support'
      fullPath: '/support'
      preLoaderRoute: typeof SupportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/feedback': {
      id: '/feedback'
      path: '/feedback'
      fullPath: '/feedback'
      preLoaderRoute: typeof FeedbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_seeker': {
      id: '/_seeker'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof SeekerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_owner': {
      id: '/_owner'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof OwnerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_admin': {
      id: '/_admin'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/seeker/signup': {
      id: '/seeker/signup'
      path: '/seeker/signup'
      fullPath: '/seeker/signup'
      preLoaderRoute: typeof SeekerSignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/seeker/login': {
      id: '/seeker/login'
      path: '/seeker/login'
      fullPath: '/seeker/login'
      preLoaderRoute: typeof SeekerLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/owner/signup': {
      id: '/owner/signup'
      path: '/owner/signup'
      fullPath: '/owner/signup'
      preLoaderRoute: typeof OwnerSignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/owner/login': {
      id: '/owner/login'
      path: '/owner/login'
      fullPath: '/owner/login'
      preLoaderRoute: typeof OwnerLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_seeker/seeker': {
      id: '/_seeker/seeker'
      path: '/seeker'
      fullPath: '/seeker'
      preLoaderRoute: typeof SeekerSeekerRouteImport
      parentRoute: typeof SeekerRoute
    }
    '/_seeker/saved': {
      id: '/_seeker/saved'
      path: '/saved'
      fullPath: '/saved'
      preLoaderRoute: typeof SeekerSavedRouteImport
      parentRoute: typeof SeekerRoute
    }
    '/_seeker/browse': {
      id: '/_seeker/browse'
      path: '/browse'
      fullPath: '/browse'
      preLoaderRoute: typeof SeekerBrowseRouteImport
      parentRoute: typeof SeekerRoute
    }
    '/_owner/publish': {
      id: '/_owner/publish'
      path: '/publish'
      fullPath: '/publish'
      preLoaderRoute: typeof OwnerPublishRouteImport
      parentRoute: typeof OwnerRoute
    }
    '/_owner/owner': {
      id: '/_owner/owner'
      path: '/owner'
      fullPath: '/owner'
      preLoaderRoute: typeof OwnerOwnerRouteImport
      parentRoute: typeof OwnerRoute
    }
    '/_admin/admin': {
      id: '/_admin/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminAdminRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_seeker/spaces/$id': {
      id: '/_seeker/spaces/$id'
      path: '/spaces/$id'
      fullPath: '/spaces/$id'
      preLoaderRoute: typeof SeekerSpacesIdRouteImport
      parentRoute: typeof SeekerRoute
    }
  }
}

interface AdminRouteChildren {
  AdminAdminRoute: typeof AdminAdminRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAdminRoute: AdminAdminRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface OwnerRouteChildren {
  OwnerOwnerRoute: typeof OwnerOwnerRoute
  OwnerPublishRoute: typeof OwnerPublishRoute
}

const OwnerRouteChildren: OwnerRouteChildren = {
  OwnerOwnerRoute: OwnerOwnerRoute,
  OwnerPublishRoute: OwnerPublishRoute,
}

const OwnerRouteWithChildren = OwnerRoute._addFileChildren(OwnerRouteChildren)

interface SeekerRouteChildren {
  SeekerBrowseRoute: typeof SeekerBrowseRoute
  SeekerSavedRoute: typeof SeekerSavedRoute
  SeekerSeekerRoute: typeof SeekerSeekerRoute
  SeekerSpacesIdRoute: typeof SeekerSpacesIdRoute
}

const SeekerRouteChildren: SeekerRouteChildren = {
  SeekerBrowseRoute: SeekerBrowseRoute,
  SeekerSavedRoute: SeekerSavedRoute,
  SeekerSeekerRoute: SeekerSeekerRoute,
  SeekerSpacesIdRoute: SeekerSpacesIdRoute,
}

const SeekerRouteWithChildren =
  SeekerRoute._addFileChildren(SeekerRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  OwnerRoute: OwnerRouteWithChildren,
  SeekerRoute: SeekerRouteWithChildren,
  FeedbackRoute: FeedbackRoute,
  SupportRoute: SupportRoute,
  OwnerLoginRoute: OwnerLoginRoute,
  OwnerSignupRoute: OwnerSignupRoute,
  SeekerLoginRoute: SeekerLoginRoute,
  SeekerSignupRoute: SeekerSignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
